<?php
namespace App;


class Constant
{

const ORDER_STATUS_CREATED = 'CREATED';
const ORDER_STATUS_PAYED = 'PAYED';
const ORDER_STATUS_REJECTED = 'REJECTED';

const ORDER_VALUE_DEFAULT = 30000;
const ORDER_CURRENCY_DEFAULT = 'COP';

}
